// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-zhuzYAOem4lRgsDp20onNyNJqqoTo4M',
    appId: '1:509485762295:web:e37bde6c8a2ab9721475f2',
    messagingSenderId: '509485762295',
    projectId: 'bevistoria',
    authDomain: 'bevistoria.firebaseapp.com',
    storageBucket: 'bevistoria.appspot.com',
    measurementId: 'G-85JJ8KC6KG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZjPwpq7uI3_WvO0f7d04fhgQjS5AwsQw',
    appId: '1:509485762295:android:f67953d13fe8074b1475f2',
    messagingSenderId: '509485762295',
    projectId: 'bevistoria',
    storageBucket: 'bevistoria.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAn-DryEdDLFL68_c5VTfIk2E8OWTxqbRY',
    appId: '1:509485762295:ios:44485f8564d16ed01475f2',
    messagingSenderId: '509485762295',
    projectId: 'bevistoria',
    storageBucket: 'bevistoria.appspot.com',
    androidClientId: '509485762295-226f321nb62h2gd0cjig9d1f33i6ufd8.apps.googleusercontent.com',
    iosBundleId: 'com.example.testFirebasePush',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAn-DryEdDLFL68_c5VTfIk2E8OWTxqbRY',
    appId: '1:509485762295:ios:42ce03d2db71d3bb1475f2',
    messagingSenderId: '509485762295',
    projectId: 'bevistoria',
    storageBucket: 'bevistoria.appspot.com',
    androidClientId: '509485762295-226f321nb62h2gd0cjig9d1f33i6ufd8.apps.googleusercontent.com',
    iosBundleId: 'com.example.testFirebasePush.RunnerTests',
  );
}
